# Generated by Django 5.2 on 2025-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=500)),
                ('Last_Name', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('AddressLine1', models.CharField(max_length=500)),
                ('AddressLine2', models.CharField(max_length=500)),
                ('District', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('PINCode', models.IntegerField()),
                ('Username', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('ConfirmPSW', models.CharField(max_length=500)),
            ],
        ),
    ]
