# Generated by Django 5.2 on 2025-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Birth_Date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='PINCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
