# Generated by Django 5.2 on 2025-05-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_app', '0004_alter_account_email_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line1',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
