# Generated by Django 5.2 on 2025-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_app', '0005_alter_account_address_line1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
