# Generated by Django 5.2 on 2025-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_app', '0007_alter_account_address_line1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
