# Generated by Django 5.2 on 2025-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_app', '0008_remove_account_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
