# Generated by Django 5.2 on 2025-04-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
