# Generated by Django 5.2 on 2025-04-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Available',
            new_name='Availability',
        ),
    ]
