# Generated by Django 5.2 on 2025-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
