# Generated by Django 5.2 on 2025-04-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_alter_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Description',
        ),
        migrations.AddField(
            model_name='product',
            name='Material',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Wash_Care',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
