# Generated by Django 5.2 on 2025-04-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_remove_product_description_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.CharField(max_length=100),
        ),
    ]
