# Generated by Django 5.2 on 2025-04-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Stock',
            field=models.CharField(max_length=100),
        ),
    ]
