# Generated by Django 5.2 on 2025-04-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Colour',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
