# Generated by Django 5.2 on 2025-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0010_category_top_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Best_Seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='New_Launch',
            field=models.BooleanField(default=False),
        ),
    ]
