# Generated by Django 5.2 on 2025-05-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0012_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
