# Generated by Django 5.2 on 2025-05-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0015_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
