# Generated by Django 5.2 on 2025-05-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0016_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
